### PR TITLE
Code reiew rquest

### PR DESCRIPTION
**Pull request by uchennaanya**
This is the clone of the News Week web site. It has been built with Bootstrap 4. We used very few css codes.

1. Has input fields for email and search
2. Has sign-up button
3. Has sign-in button
4. Has different links for privacy policy, privacy statement and terms of use
5. Has a footer with different links for legal, security and privacy.
6. Has Images

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## :wave: :wave: Hello @Naqhid and @uchennaanya!!! Great  work!

Things to notice:
:100: Descriptive PR
:100: Descriptive README
:100: The project has a Licence

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] We should set up the linters before submititting for a review and check all linter checks pass. [LINK](https://github.com/microverseinc/linters-config/tree/master/html)

- [x] Add to ```.gitignore``` the files that are not needed for production. 
image

- [x] Move the custom style sheet after the bootstrap CDN Link this makes it easier to override bootstrap default classes if needed.

- [x] Use semantic HTML for the footer with ```<footer>``` tag.

- [x] The ```<footer>``` should be outside the main wrapper.

- [x] ```alt=""``` attribute should always have a short and meaningful description of the image. We should add a description fo all images.

- [x] Remove the unnecessary HTML code ```<figcaption is not being used>```

- [x] Element doesn't match the original style for title and image size
image

- [x] Element doesn't match original 
image

- [x] Element doesn't match original
image

- [x] Navbar doesn't match original in tablet mode
image

- [x] my turn section surpasses the column alignment
image

- [x] Element doesn't match original in tablet view
image

- [x] Element doesn't match original in tablet view.
image

- [x] Element doesn't match original in tablet view
image

- [x] element is not aligned to the bottom
image

- [ ]Project doesn't have sticky nav bar
image

- [x] Nav bar doesn't match original in mobile view
image

- [x] More stories doesn't match original in mobile view
image

- [x] Section doesn't match original in mobile version
image

- [x] Element doesn't match original
image

- [x] Section doesn't match original
image

- [x] footer doesn't match original
image

### [OPTIONAL]  :yellow_circle:  

- [ ] Prefer 2 space indentation for HTML file. This improves readability

### [Comments] :green_circle: 

- A great tool to test if the project looks as intended in different screen sizes is the browsers media query inspector. Please use it to test the website.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).


 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Remove `node_modules` from your repo.
- [x]  Please implement suggested required changes in the Last section (Subscribe and newsletter)


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**
- [x] Please remove space between items so that it looks exactly like on the [original page.](https://www.newsweek.com/) 

**Clone**

chrome-capture (5)

**Original** 

chrome-capture (6)

- [x] Please align the text correctly as present on the [original page.](https://www.newsweek.com/) 

**Clone**

chrome-capture (7)

**Original** 

chrome-capture (8)

- [x] On scrolling sticky navbar should have less width, the date and weather section should disappear and the Newsweek logo takes their place. 
**Clone**

chrome-capture (9)

**Original** 

chrome-capture (10)

- [x] In the editor's pick, items are not aligned in a row. Please have a look. 

**Clone**

chrome-capture (11)

**Original**

chrome-capture (12)

- [x] For all of these sections the height of images should be greater than the text as on the [original page.](https://www.newsweek.com/)  

**Clone**

chrome-capture (13)

**Original**

chrome-capture (14)

- [ ] You are missing the subscribe and Free SignUp button in this spat of the webpage. Your image has a greater height as compared to the original one. Your text is in black color. Please change it to red 

**Clone**

chrome-capture (16)

- [ ] Text after logo should be aligned correctly as present on [original page.](https://www.newsweek.com/) 

**Clone**

chrome-capture (17)

**Original**

chrome-capture (18)


**Original**

chrome-capture (15)

- [x] Your whole webpage has white space around edges. Please remove that. 

- [x] You have copy-pasted the same items and images gain and again. Please try to use different text and images so that It looks great. 

- [x] My turn section has an alignment problem. Please fix that.
95763891-4e578e80-0c75-11eb-8350-b3259e1d4f8b

- [x] Please again have a look at the very first review. None of the changes requested by my Respected TSE on your website has done. Please work on those too. 

In the case of any confusion please reach to me on slack **arslanbisharat**. Or you can reach out to Full-Time TSE for 1:1 meeting. 

**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Great job so far guys :clap: :clap: :clap:, you are almost there, just some couple changes :toolbox:  and your project is approved :checkered_flag: 

- [x] as mentioned by the previous TSE, You have copy-pasted the same items and images gain and again. Please try to use different text and images so that It looks great.

- [x] add some margin-top to the main tag so the top story title will be displayed on mobile and tablet views:

|*Clone*|*Original*|
|:---:|:---:|
| image | image |

- [ ] Fix the newsletter section it's not well displayed:
image

- [ ] Fix this form on mobile view:

|*Clone*|*Original*|
|:---:|:---:|
| image | image |

- [ ] on tablet view the subscribe and newsletter sections are overlapping:
image

- [ ] in the newsletter section use the same image as in the original, and make sure that the image is not stretched you can use `object-fit: cover;` to fix that:

|*Clone*|*Original*|
|:---:|:---:|
| image | image |

- [ ] Fix linter errors:
image

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
### Changes Requested

Thank you for submitting this project. 

- [ ] Actually, your project is messed up. Everything has more than enough size and everything is not working fine. 
Please have a look at your webpage

- [ ] Please resolve your linter errors. 

**After making changes please submit another review.** 

Regards,
Arslan Bisharat
slack: arslanbisharat

**Review by Rhelli — CHANGES_REQUESTED** [review]
# Changes Required 🛑♻️

Hi @uchennaanya, well done on the project so far. You've managed to create a pretty close clone to the Next Web. There are however some changes that need to be made in order to get you're project approved. Please assess the changes I am about to propose as well as any the previous TSEs have made before me and we'll be able to get your project approved and get you onto the next project in no time!

******

1. **[Mandatory]** - Please fix the 'Newsletter' page element's appearance. This is how it appears on small screens 👇🏽

image

**This is how it should appear** 👇🏽

image

**Fix:** Get rid of the red border and ensure the image is 100% width of its container.

*******

2. **[Mandatory]** - Please fix this overlapping text and story topics. This appears on mobile 👇🏽

image

It should appear like this 👇🏽

image

**Fix:** Give the container which holds the story type (i.e. 'Features') and the story topic (i.e. 'Culture' a fixed width. Then give that container a property of `margin-right: auto`. Alternatively, make the container `width: 100%` and then make it a flexbox and give it the property `justify-content: flex-start;`.

****

3. **[Mandatory]** - Please fix the width of the entire page. This appears on not only small screens. Here is your version 👇🏽

image

Here is Newsweek's version  👇🏽
image

******

4. **[Mandatory]** - Please fix this squashed 'In The Magazine' feature image. 

Here is your version (small screen)  👇🏽

image

Here is the Newsweek version 👇🏽

image

**Fix:** Set the image to `height: 100%;`. If you are having trouble with the image being too wide at 100% height, ensure the image you have in your assests is the image from Newsweeks website at the screen size you intend to use it at (they use different sizes).

*******

5. **[Mandatory]** - Please fix the text wrapping and image alignment in the 'More Stories' section (small screen size).

Here is your version 👇🏽

image

Here is the Newsweek version 👇🏽

image

**Fix:** Reduce your font size.

*****

6. **[Mandatory]** - Please fix the appearence of the 'Opinions' section. This appears on small screen sizes.

Your version 👇🏽

image

Newsweeks Version 👇🏽
image


**Fix:** Again, reduce you font sizes. Use the Chrome Dev tool to inspect the original sites font sizes for accuracy.

*******

7. **[Mandatory]** - Please fix the appearance of your 'Editors Pick' section. At medium screen sizes, it should have 2 stories per row, not 4 as yours is.

Your version 👇🏽

image

Newsweeks version 👇🏽

image

********

8. **[Mandatory]** - Large font sizes are making the topics sections too large. Please reduce the font sizes.

Your version 👇🏽

image


Newsweeks version 👇🏽

image

*******

9. **[Mandatory]** - Please remove the red border around the newsletter element. This is on medium screens.

Your version 👇🏽

image



Newsweeks version 👇🏽

image

********

10. **[Mandatory]** - Please fix your navbar's appearance on medium screens and prevent the text from wrapping.

Your version 👇🏽

image


Newsweeks version 👇🏽

image


*******

11. **[Mandatory]** - Please fix the appearence of the Newsletter element on large screens.

Your version 👇🏽

image


Newsweeks version 👇🏽

image

**********

Don't be disheartened by the number of changes asked of you - if its challenging, you'll come out the other side stronger for it!

Get all of these changes ticked off and completed and we'll be able to approve your project and get you on to the next project! Good luck!

If you have any questions or need any help, feel free to @ me here on Github or message me in Slack.

All the best,

💂🏽‍♂️ Rory

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required

## Hello team,

**Great job on your project. However, there are changes, requested by the previous tse, that haven't been implemented yet.**

1). **Your newsletter block doesn't look like the original on small screens(< 768px width).**

original | clone
---------| -------
newsletter_original | newsletter_clone

2). **The following change has not been implemented yet. Note small screen sizes start at 767px width.**

tsereview2

3). **In the screenshot below, the images should cover the space marked in red.**

2020-10-15 23_52_48-tsereview3color

4). **Check the screenshot below.**

squashed

5). **Editor's pick section**

- **The image tags should display at the bottom left of the page. The screenshots are for medium screen sizes(768px - 991px width).**

original | clone
---------| -------
editorssection_original | editorssection_clone

- **The editors pick section should display four stories per row on desktop screen sizes (> 991px width). Your page displays two stories per row.**

6). **The issue in the screenshot below is seen on medium screen sizes(>767px width).**

us_clone

7). **The issue in the screenshot below is seen at 992px width.**

navbar_clone

8). **The bottom content under more stories section is not displaying properly on 991px width.**

moreStories

9). **Fix the opinion section for desktop screen sizes(> 991px). The images are too small and side content too large.**


opinion_clone

## Optional.

- **Fix the width and height of your images so they don't look to stretched horizontally/vertically.**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :construction:

### Hi team :wave: 
Good job with the changes! :ok_hand: We are almost there.
However, we do have some changes to make before we proceed (see comments below).

**[ REQUIRED CHANGES ]** 

**Within 575px & 767px screen sizes**
- [x] Your entire page seems to be out of order. This is the main range of screen sizes where you are having most issues. I'll list some cases below, but please check the whole page and fix as appropriate.
- Your newsletter section needs to be worked on.
- You are having some blank spaces on the right side of your page. Your sections should cover these spaces.


| Original | Clone |
| ----------- | ----------- |
|  |  |
|  |  |
| Paragrap | Text |

**At large screen sizes (>=1024px)**

- [x] The `Newsletter` and `Subscribe` sections share the same height. This is not the case in your page. Kindly fix this.

Original Page:


Your Clone Page:


- [x] Please double-check the issues raised by the last reviewer and ensure that you fixed them all.

* **When you have made the specified changes, please submit another code review. Thank you!**
* **If you feel like you need help or you have any question(s), I'm @taofeekolalere on slack**

Regards,
[Taofeek Olalere](https://github.com/teekaytech)
Happy Coding :technologist:

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required.

**Great job guys. You have made a lot of progress and your page is almost looking like the original. I make the following requests because they show a noticeable difference between your page and the original page.**

1). **Fix the following changes on 992px width.**

- **The content in the middle navbar should display on a single line.**

original | clone
---------| -------
nav_original | nav_clone

-  **The image tags for images in the Editor's pick section are not wrapped properly within their allocated width/space.**

editor_clone

- **Reduce font-size for the image tags in the cultural and travel section.**

cultural_clone

- **The newsletter block looks too stretched and some sections of its content is not visible.**

original | clone
---------| -------
newsletter_original | newsletter_clone

2). **Fix the following changes on 767px width.**

- **Reduce the width of the sign-up form above the 'in the magazine section'.**

original | clone
---------| -------
signup_original | signup_clone

- **The third small image in the Tech & Science section is not well aligned.**

techscience


## Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

**Review by arslanbisharat — APPROVED** [review]
### Approved
Hello,
**I am approving this project but here are some changes which are optional but these are highly recommended.** 

- [ ]  **Optional** Please move live link from your readme a little above. 

- [ ] **Optional** Please correct these on large, medium and small screen.
chrome-capture - 2020-10-18T085143 343

- [ ] **Optional** Please remove the sticky navbar from the large screen. It doesn't look like on the original page.

- [ ] **Optional** Please remove white space. 
chrome-capture - 2020-10-18T085249 305

-----------------------------------------------------------------------------------------------
**After you are done with these changes please submit your project.** 
Regards,
Arslan Bisharat

**Pull request merged**
